"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GetStarted = GetStarted;
const jsx_runtime_1 = require("react/jsx-runtime");
const lucide_react_1 = require("lucide-react");
const Button_1 = require("../ui/Button");
function GetStarted() {
    return ((0, jsx_runtime_1.jsx)("div", { className: "bg-gray-50 py-16", children: (0, jsx_runtime_1.jsxs)("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: [(0, jsx_runtime_1.jsxs)("div", { className: "text-center", children: [(0, jsx_runtime_1.jsx)("h2", { className: "text-3xl font-extrabold text-gray-900 sm:text-4xl", children: "Get Started with RhythemicBeats" }), (0, jsx_runtime_1.jsx)("p", { className: "mt-4 text-xl text-gray-500", children: "Choose the option that best suits your needs" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "mt-12 grid grid-cols-1 gap-8 sm:grid-cols-2", children: [(0, jsx_runtime_1.jsx)("div", { className: "bg-white rounded-lg shadow-lg overflow-hidden", children: (0, jsx_runtime_1.jsxs)("div", { className: "px-6 py-8", children: [(0, jsx_runtime_1.jsx)("div", { className: "flex justify-center", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Phone, { className: "h-12 w-12 text-red-500" }) }), (0, jsx_runtime_1.jsx)("h3", { className: "mt-4 text-xl font-semibold text-center text-gray-900", children: "Book Consultation" }), (0, jsx_runtime_1.jsx)("p", { className: "mt-2 text-gray-500 text-center", children: "Schedule a free consultation with our healthcare experts" }), (0, jsx_runtime_1.jsx)("div", { className: "mt-6", children: (0, jsx_runtime_1.jsxs)(Button_1.Button, { onClick: () => window.location.href = '/consultation', className: "w-full", children: ["Book Now", (0, jsx_runtime_1.jsx)(lucide_react_1.ArrowRight, { className: "ml-2 h-5 w-5" })] }) })] }) }), (0, jsx_runtime_1.jsx)("div", { className: "bg-white rounded-lg shadow-lg overflow-hidden", children: (0, jsx_runtime_1.jsxs)("div", { className: "px-6 py-8", children: [(0, jsx_runtime_1.jsx)("div", { className: "flex justify-center", children: (0, jsx_runtime_1.jsx)(lucide_react_1.FileText, { className: "h-12 w-12 text-red-500" }) }), (0, jsx_runtime_1.jsx)("h3", { className: "mt-4 text-xl font-semibold text-center text-gray-900", children: "Download Guide" }), (0, jsx_runtime_1.jsx)("p", { className: "mt-2 text-gray-500 text-center", children: "Get our comprehensive guide on heart health monitoring" }), (0, jsx_runtime_1.jsx)("div", { className: "mt-6", children: (0, jsx_runtime_1.jsxs)(Button_1.Button, { onClick: () => window.location.href = '/guide', className: "w-full", children: ["Download", (0, jsx_runtime_1.jsx)(lucide_react_1.ArrowRight, { className: "ml-2 h-5 w-5" })] }) })] }) })] })] }) }));
}
//# sourceMappingURL=GetStarted.js.map