import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Package, Shield, CreditCard } from 'lucide-react';
function Button({ children, className }) {
    return (_jsx("button", { className: `w-full ${className ? className : ''} py-3 px-6 bg-blue-500 text-white font-bold rounded-lg hover:bg-blue-600 transition`, children: children }));
}
// Purchase Component
export function Purchase() {
    return (_jsx("div", { className: "min-h-screen bg-gray-50 pt-20", children: _jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12", children: [_jsx("h1", { className: "text-4xl font-bold text-gray-900 text-center", children: "Purchase RhythemicBeats" }), _jsxs("div", { className: "mt-12 grid grid-cols-1 gap-8 lg:grid-cols-2", children: [_jsxs("div", { className: "bg-white rounded-lg shadow-lg p-8", children: [_jsx("h2", { className: "text-2xl font-semibold text-gray-900", children: "Device Specifications" }), _jsxs("ul", { className: "mt-6 space-y-4", children: [_jsxs("li", { className: "flex items-center", children: [_jsx(Package, { className: "h-5 w-5 text-red-500 mr-3" }), _jsx("span", { children: "Advanced Arduino UNO-based ECG monitoring" })] }), _jsxs("li", { className: "flex items-center", children: [_jsx(Shield, { className: "h-5 w-5 text-red-500 mr-3" }), _jsx("span", { children: "FDA-approved technology" })] }), _jsxs("li", { className: "flex items-center", children: [_jsx(CreditCard, { className: "h-5 w-5 text-red-500 mr-3" }), _jsx("span", { children: "1-year warranty included" })] })] }), _jsxs("div", { className: "mt-8", children: [_jsx("div", { className: "text-4xl font-bold text-gray-900", children: "$299.99" }), _jsx("p", { className: "mt-2 text-gray-500", children: "Free shipping worldwide" })] }), _jsx(Button, { className: "mt-8", children: "Add to Cart" })] }), _jsxs("div", { className: "bg-white rounded-lg shadow-lg p-8", children: [_jsx("h2", { className: "text-2xl font-semibold text-gray-900", children: "What's Included" }), _jsxs("ul", { className: "mt-6 space-y-4", children: [_jsx("li", { children: "RhythemicBeats ECG Device" }), _jsx("li", { children: "USB Cable" }), _jsx("li", { children: "Electrode Pads (Pack of 10)" }), _jsx("li", { children: "Quick Start Guide" }), _jsx("li", { children: "Mobile App Access" }), _jsx("li", { children: "24/7 Technical Support" })] })] })] })] }) }));
}
//# sourceMappingURL=Purchase.js.map