"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ECGWaveComparison = ECGWaveComparison;
const jsx_runtime_1 = require("react/jsx-runtime");
const lucide_react_1 = require("lucide-react");
function WaveCard({ title, description, imageUrl, heartRate, warning }) {
    return ((0, jsx_runtime_1.jsxs)("div", { className: "bg-white rounded-lg shadow-lg overflow-hidden", children: [(0, jsx_runtime_1.jsxs)("div", { className: "relative", children: [(0, jsx_runtime_1.jsx)("img", { src: imageUrl, alt: `${title} ECG Wave`, className: "w-full h-48 object-cover" }), (0, jsx_runtime_1.jsxs)("div", { className: "absolute top-4 right-4 bg-white/90 px-3 py-1 rounded-full flex items-center", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Heart, { className: "h-4 w-4 text-red-500 mr-1" }), (0, jsx_runtime_1.jsx)("span", { className: "text-sm font-medium", children: heartRate })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "p-6", children: [(0, jsx_runtime_1.jsx)("h3", { className: "text-xl font-semibold text-gray-900", children: title }), (0, jsx_runtime_1.jsx)("p", { className: "mt-2 text-gray-600", children: description }), warning && ((0, jsx_runtime_1.jsxs)("div", { className: "mt-4 flex items-start bg-red-50 p-3 rounded-md", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.AlertTriangle, { className: "h-5 w-5 text-red-500 mt-0.5 flex-shrink-0" }), (0, jsx_runtime_1.jsx)("p", { className: "ml-3 text-sm text-red-700", children: warning })] }))] })] }));
}
function ECGWaveComparison() {
    return ((0, jsx_runtime_1.jsxs)("div", { className: "py-12", children: [(0, jsx_runtime_1.jsx)("h3", { className: "text-2xl font-bold text-gray-900 mb-8", children: "Understanding ECG Wave Patterns" }), (0, jsx_runtime_1.jsxs)("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-8", children: [(0, jsx_runtime_1.jsx)(WaveCard, { title: "Normal Sinus Rhythm", description: "Regular heart rhythm with consistent spacing between beats and normal P waves, QRS complexes, and T waves.", imageUrl: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=80", heartRate: "60-100 BPM" }), (0, jsx_runtime_1.jsx)(WaveCard, { title: "Tachycardia", description: "Abnormally fast heart rate with shortened intervals between beats. May indicate stress, anxiety, or underlying heart conditions.", imageUrl: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80", heartRate: ">100 BPM", warning: "Seek medical attention if accompanied by chest pain, shortness of breath, or dizziness." }), (0, jsx_runtime_1.jsx)(WaveCard, { title: "Bradycardia", description: "Slower than normal heart rate with extended intervals between beats. Can be normal during sleep but may indicate heart block or other conditions.", imageUrl: "https://images.unsplash.com/photo-1576091160391-31906e2e357b?auto=format&fit=crop&w=800&q=80", heartRate: "<60 BPM", warning: "Consult a healthcare provider if experiencing fatigue, weakness, or fainting spells." })] })] }));
}
//# sourceMappingURL=ECGWaveComparison.js.map