"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Guide = Guide;
const jsx_runtime_1 = require("react/jsx-runtime");
const lucide_react_1 = require("lucide-react");
function Button({ children, className = '', disabled = false, type = 'button', }) {
    return ((0, jsx_runtime_1.jsx)("button", { type: type, className: `py-3 px-6 bg-blue-500 text-white font-bold rounded-lg hover:bg-blue-600 transition ${className}`, disabled: disabled, children: children }));
}
// Guide Component
function Guide() {
    return ((0, jsx_runtime_1.jsx)("div", { className: "min-h-screen bg-gray-50 pt-20", children: (0, jsx_runtime_1.jsxs)("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12", children: [(0, jsx_runtime_1.jsx)("h1", { className: "text-4xl font-bold text-gray-900 text-center", children: "Heart Health Monitoring Guide" }), (0, jsx_runtime_1.jsx)("p", { className: "mt-4 text-xl text-gray-500 text-center", children: "Download our comprehensive guide to heart health monitoring" }), (0, jsx_runtime_1.jsxs)("div", { className: "mt-12 grid grid-cols-1 gap-8 lg:grid-cols-2", children: [(0, jsx_runtime_1.jsxs)("div", { className: "bg-white rounded-lg shadow-lg p-8", children: [(0, jsx_runtime_1.jsx)("h2", { className: "text-2xl font-semibold text-gray-900", children: "What's Inside" }), (0, jsx_runtime_1.jsxs)("ul", { className: "mt-6 space-y-4", children: [(0, jsx_runtime_1.jsxs)("li", { className: "flex items-center", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.FileText, { className: "h-5 w-5 text-red-500 mr-3" }), (0, jsx_runtime_1.jsx)("span", { children: "Understanding ECG Basics" })] }), (0, jsx_runtime_1.jsxs)("li", { className: "flex items-center", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Book, { className: "h-5 w-5 text-red-500 mr-3" }), (0, jsx_runtime_1.jsx)("span", { children: "Heart Health Best Practices" })] }), (0, jsx_runtime_1.jsxs)("li", { className: "flex items-center", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Download, { className: "h-5 w-5 text-red-500 mr-3" }), (0, jsx_runtime_1.jsx)("span", { children: "Device Usage Instructions" })] })] }), (0, jsx_runtime_1.jsxs)(Button, { className: "w-full mt-8", children: ["Download Guide", (0, jsx_runtime_1.jsx)(lucide_react_1.Download, { className: "ml-2 h-5 w-5" })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "bg-white rounded-lg shadow-lg p-8", children: [(0, jsx_runtime_1.jsx)("h2", { className: "text-2xl font-semibold text-gray-900", children: "Guide Preview" }), (0, jsx_runtime_1.jsx)("div", { className: "mt-6 aspect-w-16 aspect-h-9", children: (0, jsx_runtime_1.jsx)("img", { src: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=80", alt: "Guide Preview", className: "rounded-lg object-cover" }) })] })] })] }) }));
}
//# sourceMappingURL=Guide.js.map