"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Purchase = Purchase;
const jsx_runtime_1 = require("react/jsx-runtime");
const lucide_react_1 = require("lucide-react");
function Button({ children, className }) {
    return ((0, jsx_runtime_1.jsx)("button", { className: `w-full ${className ? className : ''} py-3 px-6 bg-blue-500 text-white font-bold rounded-lg hover:bg-blue-600 transition`, children: children }));
}
// Purchase Component
function Purchase() {
    return ((0, jsx_runtime_1.jsx)("div", { className: "min-h-screen bg-gray-50 pt-20", children: (0, jsx_runtime_1.jsxs)("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12", children: [(0, jsx_runtime_1.jsx)("h1", { className: "text-4xl font-bold text-gray-900 text-center", children: "Purchase RhythemicBeats" }), (0, jsx_runtime_1.jsxs)("div", { className: "mt-12 grid grid-cols-1 gap-8 lg:grid-cols-2", children: [(0, jsx_runtime_1.jsxs)("div", { className: "bg-white rounded-lg shadow-lg p-8", children: [(0, jsx_runtime_1.jsx)("h2", { className: "text-2xl font-semibold text-gray-900", children: "Device Specifications" }), (0, jsx_runtime_1.jsxs)("ul", { className: "mt-6 space-y-4", children: [(0, jsx_runtime_1.jsxs)("li", { className: "flex items-center", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Package, { className: "h-5 w-5 text-red-500 mr-3" }), (0, jsx_runtime_1.jsx)("span", { children: "Advanced Arduino UNO-based ECG monitoring" })] }), (0, jsx_runtime_1.jsxs)("li", { className: "flex items-center", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Shield, { className: "h-5 w-5 text-red-500 mr-3" }), (0, jsx_runtime_1.jsx)("span", { children: "FDA-approved technology" })] }), (0, jsx_runtime_1.jsxs)("li", { className: "flex items-center", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.CreditCard, { className: "h-5 w-5 text-red-500 mr-3" }), (0, jsx_runtime_1.jsx)("span", { children: "1-year warranty included" })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "mt-8", children: [(0, jsx_runtime_1.jsx)("div", { className: "text-4xl font-bold text-gray-900", children: "$299.99" }), (0, jsx_runtime_1.jsx)("p", { className: "mt-2 text-gray-500", children: "Free shipping worldwide" })] }), (0, jsx_runtime_1.jsx)(Button, { className: "mt-8", children: "Add to Cart" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "bg-white rounded-lg shadow-lg p-8", children: [(0, jsx_runtime_1.jsx)("h2", { className: "text-2xl font-semibold text-gray-900", children: "What's Included" }), (0, jsx_runtime_1.jsxs)("ul", { className: "mt-6 space-y-4", children: [(0, jsx_runtime_1.jsx)("li", { children: "RhythemicBeats ECG Device" }), (0, jsx_runtime_1.jsx)("li", { children: "USB Cable" }), (0, jsx_runtime_1.jsx)("li", { children: "Electrode Pads (Pack of 10)" }), (0, jsx_runtime_1.jsx)("li", { children: "Quick Start Guide" }), (0, jsx_runtime_1.jsx)("li", { children: "Mobile App Access" }), (0, jsx_runtime_1.jsx)("li", { children: "24/7 Technical Support" })] })] })] })] }) }));
}
//# sourceMappingURL=Purchase.js.map